language: python

stages:
  - style-check
  - test

jobs:
  include:
    - stage: style-check
      python: '3.6'
      install: 
        - pip3 install -r requirements.txt -r requirements.dev.txt
        - pip3 install black
      script: make style-check
    - stage: test
      python: '3.6'
      install: 
      - pip3 install -r requirements.txt -r requirements.dev.txt
      - pip3 install codecov
      script: make test
      after_success: codecov
    - stage: test
      python: '3.5'
      install: pip3 install -r requirements.txt -r requirements.dev.txt
      script: make test
    - stage: test
      name: docs
      install: pip3 install -r requirements.txt -r requirements.dev.txt
      script: make doc
