language: python

stages:
  - style-check
  - test
  - name: doc
    if: branch = master
  - name: deploy
    if: branch = master
  - name: release
    if: tag IS present


jobs:
  include:
    - stage: style-check
      python: '3.6'
      install: 
        - pip3 install -r requirements.txt -r requirements.dev.txt
        - pip3 install black
      script: make style-check
    - stage: test
      python: '3.6'
      install: pip3 install -r requirements.txt -r requirements.dev.txt
      script: make test
    - stage: test
      python: '3.5'
      install: pip3 install -r requirements.txt -r requirements.dev.txt
      script: make test
    - stage: doc
      script: skip
      deploy: true
    - stage: deploy
      script: skip
      deploy: true
    - stage: release
      script: skip
      deploy: true