language: python
python:
  - '3.6'
  - '3.5'
install: pip3 install -r requirements.txt -r requirements.dev.txt

jobs:
  include:
    - stage: style-check
      script: pip3 install black & make style-check
    - stage: test
      script: make test
#     - stage: deploy
#       script: ./deploy